<a href="https://colab.research.google.com/github/manojcsathreya/Pandas/blob/main/9_Pandas_Data_Transformations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [ ]:
#To Find Duplicate Values
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [ ]:
#to drop duplicate values
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [ ]:
data['c'] = range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [ ]:
#To find the duplicate values w.r.t some columns
data.duplicated(['a','b'])

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [ ]:
#To mark first elements as duplicate
data.duplicated(['a','b'],keep='last')

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [ ]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [ ]:
#Mapping operations

In [ ]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [ ]:
classes

{'Tim': 'A', 'Tom': 'A', 'Sam': 'B', 'Kate': 'B', 'Kim': 'B'}

In [ ]:
n=df['names'].str.capitalize()
print(n,type(n))

0     Tim
1     Tom
2     Sam
3    Kate
4     Kim
Name: names, dtype: object <class 'pandas.core.series.Series'>


In [ ]:
df['branches']= n.map(classes)

In [ ]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [ ]:
  #Replacing values in Pandas

In [ ]:
  s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [ ]:
import numpy as np

In [ ]:
s.replace(70,np.NaN)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [ ]:
s

0    80
1    70
2    90
3    60
dtype: int64

In [ ]:
#we can replace multiple values with multiple values 
s.replace([60,70],[np.NaN, 0])

0    80.0
1     0.0
2    90.0
3     NaN
dtype: float64

In [ ]:
#or we can also use dictonaries
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [ ]:
s

0    80
1    70
2    90
3    60
dtype: int64

In [ ]:
df = pd.DataFrame(np.arange(12).reshape(3,4),index=[0,1,2], columns=['tim','tom','kim','sam'])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [ ]:
s = pd.Series(['one','two','three'])
s

0      one
1      two
2    three
dtype: object

In [ ]:
df.index = df.index.map(s)

In [ ]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [ ]:
df.rename(index = str.title, columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [ ]:
#You can rename in the dictionary way
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

Cutting in pandas.
What is cutting? Say we have a series of data, we want to classify each data in that series to a defined intervals, we can use cutting

In [ ]:
df = pd.DataFrame(range(0,12))

In [ ]:
df

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [ ]:
df['age'] = [30,80,40,90,60,45,95,75,55,100,65,85]

In [ ]:
df

0  age
0    0   30
1    1   80
2    2   40
3    3   90
4    4   60
5    5   45
6    6   95
7    7   75
8    8   55
9    9  100
10  10   65
11  11   85

In [ ]:
bins = [20,40,60,80,100]
names= ['Young','Adult','senior','super-senior']

In [ ]:
df['category'] = pd.cut(df['age'],bins,labels=names)

In [ ]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]
x=[20,40,60,80,100]

In [ ]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [ ]:
#to describe under what does the elements of the dataset belongs to, we use
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [ ]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [ ]:
pd.value_counts(y)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [ ]:
#this includes the left interval value but excludes the right interval values 
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [ ]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [ ]:
#we can also divide the dataset to fall under the number of bins we specify

In [ ]:
a = pd.cut(sc,10)

In [ ]:
a.codes

array([0, 7, 1, 8, 4, 2, 9, 6, 3, 9, 4, 7], dtype=int8)

In [46]:
a.categories

IntervalIndex([(29.93, 37.0], (37.0, 44.0], (44.0, 51.0], (51.0, 58.0], (58.0, 65.0], (65.0, 72.0], (72.0, 79.0], (79.0, 86.0], (86.0, 93.0], (93.0, 100.0]], dtype='interval[float64, right]')

qcut: divies the data into specified number of bins

In [47]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(-2.259, -0.483], (0.519, 3.615], (-0.483, -0.065], (-0.483, -0.065], (-2.259, -0.483], ..., (-0.065, 0.519], (-0.065, 0.519], (0.519, 3.615], (-2.259, -0.483], (-0.483, -0.065]]
Length: 100
Categories (4, interval[float64, right]): [(-2.259, -0.483] < (-0.483, -0.065] < (-0.065, 0.519] <
                                           (0.519, 3.615]]

In [48]:
pd.value_counts(c)

(-2.259, -0.483]    25
(-0.483, -0.065]    25
(-0.065, 0.519]     25
(0.519, 3.615]      25
dtype: int64

Finding the specific values in a dataset

In [49]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0  0.905751  0.829778 -0.254146 -1.790707
1  1.379642  0.769229  0.171597  1.146969
2 -0.753536 -1.145018  0.616890 -1.903497
3 -1.218778  1.932098  0.883466  0.417120
4  1.399096  2.021148 -0.766328 -0.693352

In [51]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.060110    -0.046957     0.094063    -0.027643
std       1.032133     0.969533     1.011963     1.028659
min      -3.664146    -4.254523    -3.162688    -3.894353
25%      -0.747751    -0.662427    -0.556138    -0.702048
50%      -0.092743    -0.047787     0.072136    -0.055627
75%       0.575435     0.566725     0.768902     0.618875
max       3.099634     2.807693     2.938623     3.364890

For example, let’s find values whose absolute value exceeds 3 in a column with 3 index. To show this, I’m going to assign the column with the 1st index of the data to the col variable.

In [52]:
col = data[3]

In [55]:
col[np.abs(col)>3]

143    3.364890
492   -3.894353
502   -3.239189
593   -3.011996
Name: 3, dtype: float64

To find rows with at least one absolute value exceeding 3 in the entire data set, you can use the any method.

In [59]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
134 -1.374615 -0.340260 -3.162688  0.359025
143 -0.248942 -0.399660  1.017226  3.364890
299 -3.241859  0.917781 -0.834250  0.217875
374  3.099634 -0.334508 -0.471893  0.302626
492 -1.073596  0.138407  0.444983 -3.894353
502  1.286919  1.191143  0.477393 -3.239189
504 -3.664146  0.395431  1.978199  0.381077
593  0.756526 -1.172789  0.758834 -3.011996
695  3.072377  0.708087  1.238475  0.267853
732  0.516423 -4.254523  1.079514  0.261444

7.Selecting

In [62]:
data=pd.DataFrame(np.arange(0,12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [65]:
rw = np.random.permutation(4)
rw

array([1, 3, 0, 2])

In [66]:
data.take(rw)

0   1   2
1  3   4   5
3  9  10  11
0  0   1   2
2  6   7   8

to randomly select a row

In [69]:
data.sample()

0  1  2
2  6  7  8

to randomly select specified number of rows

In [70]:
data.sample(n=2)

0   1   2
1  3   4   5
3  9  10  11

Dummy variables

In [71]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [72]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [73]:
data=np.random.randn(10)
data

array([ 0.64130952, -1.5578743 , -0.05348791,  0.35884562, -1.48398112,
       -0.49653966, -0.17895877,  0.26582614, -0.01664839,  0.85841258])

In [74]:
pd.get_dummies(pd.cut(data,4))

(-1.56, -0.954]  (-0.954, -0.35]  (-0.35, 0.254]  (0.254, 0.858]
0                0                0               0               1
1                1                0               0               0
2                0                0               1               0
3                0                0               0               1
4                1                0               0               0
5                0                1               0               0
6                0                0               1               0
7                0                0               0               1
8                0                0               1               0
9                0                0               0               1